name: Fail Test

on:
  workflow_dispatch:  # 只能手動觸發，不會自動執行

jobs:
  fail-job:
    runs-on: ubuntu-latest

    steps:
      - name: This will fail
        run: exit 1

      - name: This won't run
        run: echo "You won't see this"
